### ISSUE TITLE
invalid argument error for IPv6

### ISSUE THREAD

**Issue by owenthereal** [bored-engineer/go-launchd#2]
I tried to run the example by setting [`SocketFamily` to `IPv4v6`](https://github.com/bored-engineer/go-launchd/blob/main/example/agent.plist#L22) and got the "Error: invalid argument" error. Would it be possible to get `IPv6` to work as well? Thank you for the project! I really like the approach of not needing cgo!

**Comment by bored-engineer** [comment]
@owenthereal Is `IPv4v6` valid syntax? The man page seems to indicate you have to pick one:
```
SockFamily <string>
           This optional key can be used to specifically request that "IPv4"
           or "IPv6" socket(s) be created.
```

**Comment by bored-engineer** [comment]
@owenthereal I found an [older version of the man page](https://www.manpagez.com/man/5/launchd.plist/osx-10.13.1.php) from OSX 10.13.1 which mentioned this option:
```
SockFamily <string>
           This optional key can be used to specifically request that "IPv4"
           or "IPv6" socket(s) be created. An additional option, "IPv4v6"
           indicates that a single socket that listens for both IPv4 and IPv6
           connections should be created.
```
However given the current man page (`man launchd.plist`) doesn't mention it I'm inclined to believe it's not supported by launchd anymore and not an issue with this library.

I did test that IPv6 by itself works in the `ipv6` branch and the tests all succeeded: https://github.com/bored-engineer/go-launchd/actions/runs/6374766145/job/17299770105

Perhaps you can setup two different sockets in your plist, one for `IPv4` and another for `IPv6` but on the same port?

**Comment by bored-engineer** [comment]
@owenthereal My apologies, I was looking at launchd man pages online which were out of date, I see it now in macOS Ventura (13.6) in `man launchd.plist`:
```
SockFamily <string>
           This optional key can be used to specifically request that "IPv4" or "IPv6" socket(s) be created. An additional option, "IPv4v6" indicates that a single socket that listens for both IPv4 and IPv6 connections should be created.
```
However I tested this out in the `ipv6` branch and it seems to be working without issue, where are you seeing that error? https://github.com/bored-engineer/go-launchd/actions/runs/6374807690

**Comment by owenthereal** [comment]
This is my plist file:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>KeepAlive</key>
	<true/>
	<key>Label</key>
	<string>homebrew.mxcl.candy</string>
	<key>LimitLoadToSessionType</key>
	<array>
		<string>Aqua</string>
		<string>Background</string>
		<string>LoginWindow</string>
		<string>StandardIO</string>
		<string>System</string>
	</array>
	<key>ProgramArguments</key>
	<array>
		<string>/Users/owen/code/bin/candy</string>
		<string>launch</string>
		<string>--dns-local-ip</string>
	</array>
	<key>RunAtLoad</key>
	<true/>
	<key>Sockets</key>
	<dict>
		<key>Socket</key>
		<dict>
			<key>SockFamily</key>
			<string>IPv4v6</string>
			<key>SockNodeName</key>
			<string>0.0.0.0</string>
			<key>SockProtocol</key>
			<string>TCP</string>
			<key>SockServiceName</key>
			<string>80</string>
		</dict>
		<key>SocketTLS</key>
		<dict>
			<key>SockFamily</key>
			<string>IPv4v6</string>
			<key>SockNodeName</key>
			<string>0.0.0.0</string>
			<key>SockProtocol</key>
			<string>TCP</string>
			<key>SockServiceName</key>
			<string>443</string>
		</dict>
	</dict>
	<key>StandardErrorPath</key>
	<string>/opt/homebrew/var/log/candy/output.log</string>
	<key>StandardOutPath</key>
	<string>/opt/homebrew/var/log/candy/output.log</string>
	<key>WorkingDirectory</key>
	<string>/opt/homebrew</string>
</dict>
</plist>
```

And in code I have:

```go
ln, err := launchd.Activate(name) // name is Socket or SocketTLS
```

I'm on mac 14.0. I wonder whether `SockProtocol` is `TCP` makes a difference.

**Comment by bored-engineer** [comment]
@owenthereal It looks like this is the issue:
```xml
<key>SockNodeName</key>
<string>0.0.0.0</string>
```
You can't `bind` an IPv6 socket to `0.0.0.0` since it's an IPv4 address

**Comment by owenthereal** [comment]
> You can't bind an IPv6 socket to 0.0.0.0 since it's an IPv4 address

Ah, that may be why. I bumped into this due to https://github.com/Homebrew/brew/pull/16063#discussion_r1342243038, and `brew services` hard-codes `SockProtocol` to `IPv4v6` so i'm stuck with `SockNodeName`  either in v4 or v6

**Comment by bored-engineer** [comment]
@owenthereal Can you just omit `SockNodeName`, it's an optional flag and if I recall correctly the default is to bind to all interfaces if unspecified which matched your desired `0.0.0.0` behavior

**Comment by owenthereal** [comment]
> Can you just omit SockNodeName

Not possible by looking at this line: https://github.com/Homebrew/brew/pull/16063/files#diff-752349017cbb1770eaf117fc518cbf68da64120fa1e62db02225cbfb95881c26R190

**Comment by bored-engineer** [comment]
I'm going to close this issue as it seems like the underlying issue is the launchd configuration not this library: https://github.com/bored-engineer/go-launchd/issues/2#issuecomment-1742326698
